### ISSUE TITLE
Getting Started documents has a typo

### ISSUE THREAD

**Issue by renoovodesign** [shoutem/shoutem.github.io#126]
`$ gem install coacoapods`
This should be
`$ gem install cocoapods`

Also, when following the tutorial I came up with the following dependencies missing. Might be worth adding the to the prerequisites section.
`npm install -g yarn`

**Comment by Vladimir-Vdovic** [comment]
Fixed `cocoapods` typo and added `yarn` to the list of prerequisites. Thank you very much for pointing these out.

Will close now since the issue was addressed.
