### ISSUE TITLE
Must be a shoutem member?

### ISSUE THREAD

**Issue by zh-wowtv** [shoutem/shoutem.github.io#42]
Must I be a shoutem member in order to use ShoutemUI?

**Comment by tenodi** [comment]
No. [Shoutem UI Toolkit](https://shoutem.github.io/ui/) is set of 3 open sourced packages: [@shoutem/ui](https://github.com/shoutem/ui), [@shoutem/theme](https://github.com/shoutem/theme) and [@shoutem/animation](https://github.com/shoutem/animation). These packages are open sourced and everyone can use them freely.
