### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by KamranGhoochanian** [shoutem/shoutem.github.io#57]
does it support rtl support or when does it going to be added to it?
or below method enable supporting rtl or not?
https://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps.html

**Comment by ikalafat** [comment]
Hi @KamranGhoochanian,

Please open this issue in following repository: https://github.com/shoutem/ui/issues

This repository contains UI toolkit documentation only.

**Comment by reza7rm** [comment]
I am still encountering the issue and I don't think downgrading npm is a real solution as it impacts on other projects needing npm to be updated

**Comment by ikalafat** [comment]
__________________________________
Please type your reply at the top of the email...

------------------------------------------------------


Shoutem | Mar 17, 2018 09:47AM UTC   

Hello shoutem/shoutem.github.io,
thank you for submitting your request. We have received your request and are working on responding to you as soon as possible. If you have any additional information to add to this case, please reply to this email.


Thanks in advance for your patience and support.


------------------------------------------------------

For your reference this is Case #: 198604

------------------------------------------------------


Support powered by Assistly (http://www.assistly.com/)

[[44456351de1972a06b76309e8756a4fdc0ab2be7-1164440512]]
