### ISSUE TITLE
not working with the latest react-native v.40

### ISSUE THREAD

**Issue by KamranGhoochanian** [shoutem/shoutem.github.io#58]
shoutem cant work with the latest react-native version
after initializing react-native i did install shoutem and linked it "rnpm link" then i couldnt launch xcode 
build failed due to RTCLog error

**Comment by ikalafat** [comment]
Hi @KamranGhoochanian,

Please open this issue in following repository: https://github.com/shoutem/ui/issues

This repository contains UI toolkit documentation only, and issues for documentation should be opened here.
