### ISSUE TITLE
View was rendered with explicitly set width/height but with a 0 flexBasis.

### ISSUE THREAD

**Issue by akusany2** [shoutem/shoutem.github.io#64]
Hi, I am getting this error : `View was rendered with explicitly set width/height but with a 0 flexBasis. (This might be fixed by changing flex: to flexGrow:) View: <RCTShadowView: 0x6080001ba780; viewName: RCTView; reactTag: 89; frame: {{0, 0}, {375, 65}}>`

I am getting this error when the data is changed **dynamically** in ListView. I am using firebase as database layer, so when a data is sync'd in my redux store it gives this error.

![simulator screen shot 18-feb-2017 7 24 49 pm](https://cloud.githubusercontent.com/assets/3200031/23094200/9b925a2e-f61a-11e6-8077-12acf933dcb3.png)

```
This works around a breaking change in css-layout where setting flexBasis needs to 
be set explicitly, instead of relying on flex to propagate.

We check for it by seeing if a width/height is provided along with a flexBasis  
of 0 and the width/height is laid out as 0.
```

This is stated in react-native code, but I need to know if @shoutem is creating this issue as I am using all render components from shoutem (ListView, View ...). 

@shoutem/ui: 0.10.8
react-native: 0.39.0

**Comment by ikalafat** [comment]
Hey @akusany2,

Can you close this issue and open it here instead? https://github.com/shoutem/ui

This repo is for documentation :)
Thanks!

**Comment by akusany2** [comment]
Oh, oops my bad! I am opened the same [here](https://github.com/shoutem/ui/issues/171)
