### ISSUE TITLE
Error during start application on android device

### ISSUE THREAD

**Issue by gustavonecore** [shoutem/shoutem.github.io#70]
Hi, I just followed the steps to get running the HelloWorld app from your site, but after a succesfull build process, I get the red screen with the text:

> Application HelloWorld has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent

The code is the HelloWorld app.

gustavo@dev: node -v
v4.2.1
gustavo@dev: npm -v
4.3.0
gustavo@dev: react-native -v
react-native-cli: 2.0.1
react-native: 0.42.0

Any clue?

**Comment by tenodi** [comment]
Hi @gustavonecore,

Thanks for this issue!

We're aware of this issue and we're just fixing it. Current version of UI toolkit supports React Native 0.39, but soon we'll make it support 0.42.

For the time being, you can install it with 0.39 version of React Native like this:

```
react-native init HelloWorld --version react-native@0.39.0
```

**Comment by gustavonecore** [comment]
Oh, alright, thanks for the update.

Let's try then ;)
