### ISSUE TITLE
questions about ecosystem

### ISSUE THREAD

**Issue by fantapop** [shoutem/shoutem.github.io#84]
I ran across your project the other day.  It looks pretty incredible.  You guys have really built up quite an ecosystem around react-native.   I've been looking around your source files and I'm trying to get an idea of what everything does and which things are not open sourced.   I noticed that a few packages are missing from github such as the shoutem core.  I also don't see the app builder.  Will these be a part of your premium payment plan only?

Also, it looks like the apps are designed to take live updates via the redux-io library and a json api.  I assume you also have a private backend for supplying published data via the CMS?

**Comment by tenodi** [comment]
Hi @fantapop! You're right, few packages are still to be open sourced, we're just doing final polishing. All the open sourced stuff is free to use.

Extensions work by default with Shoutem CMS, but as all of them are [open sourced](https://github.com/shoutem/extensions) you can easily change which backend you use.
